name: e_hotel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.1.30  # Update to the latest
  http: ^1.2.2              # Update to the latest
  random_string: ^2.3.1
  flutter_svg: ^2.0.10
  image_picker: ^1.1.2      # Update to the latest

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0     # Update to the latest
  material_color_utilities: ^0.11.1  # Update to the latest
  test_api: ^0.7.2          # Update to the latest
  mailer: ^6.1.2             # Update to the latest
  flutter_secure_storage: ^9.2.2  # Keep this as it is

dependency_overrides:
  meta: ^1.11.0  # Override version for compatibility

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/avataaars men.svg
    - assets/avataaars men 02.svg
    - assets/avataaars men 03.svg
    - assets/avataaars men 04.svg
    - assets/avataaars men 05.svg
    - assets/avataaars men 06.svg
    - assets/avataaars Women .svg
    - assets/avataaars Women  02.svg
    - assets/avataaars Women 03.svg
    - assets/avataaars Women 05.svg
