name: e_hotel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  cupertino_icons: ^1.0.6
  google_sign_in: ^6.2.1
  http: ^1.2.1
  random_string: ^2.3.1
  flutter_svg: ^2.0.10+1
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  material_color_utilities: ^0.8.0
  test_api: ^0.6.1
  vm_service: ^13.0.0
  mailer: ^5.2.0
  flutter_secure_storage: ^9.2.2
dependency_overrides:
  meta: ^1.11.0  # Override the version of meta required by flutter_test to match leak_tracker_testing

flutter:
  uses-material-design: true

  assets:
    - assets/
